### ISSUE TITLE
Opening external links won't work

### ISSUE THREAD

**Issue by maltejur** [maltejur/discord-screenaudio#2]
This should be pretty easy to fix, just didn't have the time yet.

**Comment by maltejur** [comment]
Fixed in https://github.com/maltejur/discord-screenaudio/commit/58ecbbc6f49e49a3b54d0de59dfed1cf8ea20add

**Comment by james-still** [comment]
This one needs to be reopened. Still unable to use external links with the latest build.

**Comment by yaomtc** [comment]
Happening with 20240404.64c4303
